spring:
  datasource:
    url: jdbc:mysql://localhost:3306/scheduler
    username: localmaster
    password: qwer1234


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
